# Site settings
title: "Game Press Kit Theme"
description: "A clean and minimal Jekyll theme for game press kits"
author: "Your Name"
email: "your.email@example.com"
url: "https://your-site.github.io"
lang: "en"

# Game Basic Information
game:
  # Factsheet
  developer: "Studio Name"
  developer_description: "Studio description"
  developer_url: "#"
  release_date: "TBA"
  platforms: "TBA"
  price: "USD TBA"

  #Game Pitch
  title: "Game Title"
  description: "Game description goes here."
  history: "Game history and background story goes here."
  features:
    - "Feature 1"
    - "Feature 2"
    - "Feature 3"
  
  # Game Logo
  logo_download: "#"
  logo_files:
    - "placeholder.webp"
    - "placeholder.webp"
    - "placeholder.webp"

# Images (Images section)
images:
  - "placeholder.webp"
  - "placeholder.webp"
  - "placeholder.webp"

# Additional Links (Additional Links section)
links:
  - name: "Website"
    url: "#"
  - name: "Twitter"
    url: "#"
  - name: "Facebook"
    url: "#"

# About Studio (About Studio section)
about:
  description: "Studio description goes here."

# Team Information (Team section)
team:
  - name: "Developer Name"
    role: "Role / Position"
  - name: "Artist Name"
    role: "Role / Position"

# Contact Information (Contact section)
contact:
  inquiries:
    - name: "General Inquiries"
      email: "contact@studio.com"
    - name: "Press Inquiries"
      email: "press@studio.com"
    - name: "Business Inquiries"
      email: "business@studio.com"
  social_media:
    - name: "Twitter"
      handle: "@studio"
      url: "https://twitter.com/studio"
    - name: "Facebook"
      handle: "@studio"
      url: "https://facebook.com/studio"
    - name: "Instagram"
      handle: "@studio"
      url: "https://instagram.com/studio"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 