# Site settings
title: "Game Press Kit Theme"
description: "A clean and minimal Jekyll theme for game press kits"
author: "Your Name"
email: "your.email@example.com"
url: "https://your-site.github.io"
lang: "en"

# Google Analytics
google_analytics: "G-XXXXXXXXXX"  # Replace with your Google Analytics ID

# Game Information (Factsheet, Description, History, Features, Logo)
game:
  title: "Game Title"
  description: "Game description goes here."
  history: "Game history and background story goes here."
  features:
    - "Feature 1"
    - "Feature 2"
    - "Feature 3"
  developer: "Studio Name"
  developer_url: "#"
  release_date: "TBA"
  platforms:
    - name: "Steam"
      url: "https://store.steampowered.com/app/yourgame"
    - name: "Nintendo Switch"
      url: "https://nintendo.com/yourgame"
    - name: "PlayStation"
      url: "https://playstation.com/yourgame"
  price:
    - "USD $19.99"
    - "USD $29.99"
    - "USD $49.99"
  social:
    - name: "Twitter"
      url: "https://twitter.com/studio"
    - name: "Facebook"
      url: "https://facebook.com/studio"
    - name: "Instagram"
      url: "https://instagram.com/studio"
    - name: "YouTube"
      url: "https://youtube.com/studio"

# Logo & Icon (Logo section)
logo:
  download: "#"
  files:
    - "assets/images/placeholder.webp"

# Images (Images section)
images:
  download: "#"
  files:
    - "assets/images/placeholder.webp"
    - "assets/images/placeholder.webp"
    - "assets/images/placeholder.webp"
    - "assets/images/placeholder.webp"

# Videos (Videos section)
videos:
  - title: "Gameplay Trailer"
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    description: "Official gameplay trailer showcasing the main features"
  - title: "Developer Interview"
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    description: "Behind the scenes interview with the development team"
  - title: "Launch Trailer"
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    description: "Epic launch trailer with stunning visuals"

# Selected Articles (Selected Articles section)
selected_articles:
  - quote: "This game is absolutely amazing! A masterpiece of modern gaming."
    author: "John Doe"
    link: "https://gamingreview.com/article1"
    name: "Gaming Review"
  - quote: "Innovative gameplay mechanics that will change the industry."
    author: "Jane Smith"
    link: "https://techgaming.com/article2"
    name: "Tech Gaming"
  - quote: "A must-play experience that shouldn't be missed."
    author: "Mike Johnson"
    link: "https://indiegames.com/article3"
    name: "Indie Games Blog"

# Additional Links (Additional Links section)
links:
  - name: "Website"
    url: "#"
  - name: "Twitter"
    url: "#"
  - name: "Facebook"
    url: "#"

# About Studio (About Studio section)
about:
  description: "Studio description goes here."

# Team Information (Team section)
team:
  - name: "Developer Name"
    role: "Role / Position"
  - name: "Artist Name"
    role: "Role / Position"

# Contact Information (Contact section)
contact:
  - name: "General Inquiries"
    email: "contact@studio.com"
  - name: "Press Inquiries"
    email: "press@studio.com"
  - name: "Twitter"
    url: "https://twitter.com/studio"
  - name: "Facebook"
    url: "https://facebook.com/studio"
  - name: "Instagram"
    url: "https://instagram.com/studio"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 